name: build IDSK-PLUS

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal si es diferente
# on:
#   pull_request:
#     branches:
#       - main



jobs:
  build-idsk-plus:
    permissions: write-all 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: iDSK
            asset_name: iDSK-linux-amd64
          - os: macos-latest
            artifact_name: iDSK
            asset_name: iDSK-macos-amd64
            architecture: intel

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: make idsk
        run: |
          mkdir bin
          make clean
          make
          ls -R

      - name: Extract version from VERSION file
        id: extract_version
        run: |
          VERSION=$(cat VERSION)
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      # - name: Read release.md file
      #   run: |
      #     RELEASE_BODY=$(cat release.md)
      #     echo "::set-output name=release_body::$RELEASE_BODY"
      - name: Read release.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat GHANGELOG.md) 
          r="${r//'%'/'%25'}" 
          r="${r//$'\n'/'%0A'}" 
          r="${r//$'\r'/'%0D'}" 
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT 

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: v${{ steps.extract_version.outputs.version }}
          overwrite: true
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }}
